import { hasTemplate, isEntityId, isObj, type Obj } from "./extract";
import { isConditionLeaf } from "./conditions";
import { ACTION_KEYS } from "./interactions";

export interface Violation {
  rule: string;
  /** JSON-path-ish location inside the dashboard config */
  path: string;
  message: string;
}

/**
 * Something on the dashboard that cannot be analysed. Guests do not get it:
 * the card, row, badge, view, … at `hidden` is left out, or the action
 * there does nothing.
 */
export interface Issue extends Violation {
  hidden: string;
  effect: "hidden" | "disabled";
}

export interface Sanitized {
  /** The config without the parts listed in `issues`. */
  config: Obj;
  /** Reasons the dashboard cannot be used at all (nothing smaller to leave out). */
  blockers: Violation[];
  /** Parts left out for guests. */
  issues: Issue[];
}

const NON_ENTITY_TARGET_KEYS = ["area_id", "device_id", "label_id", "floor_id"];
/** Card types that pick entities at runtime instead of listing them. */
const DYNAMIC_CARD_TYPES = new Set(["area", "iframe"]);
/** Card types that need an explicit entity list to be analysable. */
const NEEDS_ENTITIES = new Set(["logbook", "history-graph", "statistics-graph", "statistic", "map"]);
const IMAGE_PREFIXES = ["media-source://", "/local/", "/api/image/serve/", "http://", "https://", "data:image/"];

/**
 * Removes everything from a dashboard config that cannot be safely used as an
 * allowlist source. The smallest list entry around a problem (a card, row,
 * badge, feature, section or view) is left out; a problem inside an action
 * only replaces that action with `action: none`. The allowlist must be taken
 * from the returned config, so nothing on a hidden part becomes accessible.
 *
 * With `keepPositions`, left-out list entries become `null`, so paths found
 * in the result match the original config.
 */
export function sanitize(config: Obj, { keepPositions = false } = {}): Sanitized {
  const blockers: Violation[] = [];
  const issues: Issue[] = [];
  if ("strategy" in config) {
    blockers.push(v("strategy", "$", "Dashboard is generated by a strategy; entities are computed client-side from all states"));
    return { config: {}, blockers, issues };
  }

  const ctx: Ctx = { issues, keepPositions };
  const out: Obj = {};
  for (const [key, value] of Object.entries(config)) {
    const path = `$.${key}`;
    const found: Violation[] = [];
    if (hasTemplate(value)) found.push(templateViolation(path));
    const cleaned = clean(value, path, found, ctx);
    // Top-level keys have no list entry around them: drop the key itself.
    if (found.length > 0) hide(found, path, ctx);
    else out[key] = cleaned;
  }
  return { config: out, blockers, issues };
}

/** All problems on a dashboard, whether they block it or only hide parts. */
export function validate(config: Obj): Violation[] {
  const { blockers, issues } = sanitize(config);
  return [...blockers, ...issues.map(({ rule, path, message }) => ({ rule, path, message }))];
}

interface Ctx {
  issues: Issue[];
  keepPositions: boolean;
}

function v(rule: string, path: string, message: string): Violation {
  return { rule, path, message };
}

function templateViolation(path: string): Violation {
  return v("template", path, "Templates are only allowed in markdown card content");
}

function hide(found: Violation[], hidden: string, ctx: Ctx): void {
  for (const f of found) ctx.issues.push({ ...f, hidden, effect: "hidden" });
}

/**
 * Returns the cleaned node. Problems that make the surrounding list entry
 * unusable are added to `found`; the caller leaves that entry out.
 */
function clean(node: unknown, path: string, found: Violation[], ctx: Ctx): unknown {
  if (Array.isArray(node)) {
    const out: unknown[] = [];
    node.forEach((item, i) => {
      const itemPath = `${path}[${i}]`;
      const itemFound: Violation[] = [];
      const cleaned = clean(item, itemPath, itemFound, ctx);
      if (itemFound.length === 0) out.push(cleaned);
      else {
        hide(itemFound, itemPath, ctx);
        if (ctx.keepPositions) out.push(null);
      }
    });
    return out;
  }
  if (!isObj(node)) return node;
  // Condition leaves are evaluated by HA verbatim and only ever yield true or
  // false (see conditions.ts), so templates and device ids are fine there.
  if (isConditionLeaf(node)) return node;

  const own = checkElement(node, path);
  if (own.length > 0) {
    found.push(...own);
    return node;
  }

  const type = typeof node.type === "string" ? node.type : undefined;
  const out: Obj = {};
  for (const [key, value] of Object.entries(node)) {
    const childPath = `${path}.${key}`;

    if (ACTION_KEYS.has(key) && isObj(value)) {
      const actionFound: Violation[] = [];
      checkAction(value, childPath, actionFound);
      const cleaned = clean(value, childPath, actionFound, ctx);
      if (actionFound.length > 0) {
        for (const f of actionFound) ctx.issues.push({ ...f, hidden: childPath, effect: "disabled" });
        out[key] = { action: "none" };
      } else {
        out[key] = cleaned;
      }
      continue;
    }

    if (hasTemplate(value) && !(key === "content" && type === "markdown")) {
      found.push(templateViolation(childPath));
    }
    out[key] = clean(value, childPath, found, ctx);
  }
  return out;
}

/** Problems with the element itself (its type or source); it is left out as a whole. */
function checkElement(node: Obj, path: string): Violation[] {
  const out: Violation[] = [];
  if ("strategy" in node) {
    out.push(v("strategy", path, "View is generated by a strategy; entities are computed client-side from all states"));
  }

  const type = typeof node.type === "string" ? node.type : undefined;
  if (type) {
    if (type.startsWith("custom:")) {
      out.push(v("custom-card", path, `Custom element "${type}" cannot be analysed`));
    } else if (DYNAMIC_CARD_TYPES.has(type)) {
      out.push(v("dynamic-card", path, `Card type "${type}" is not allowed on guest dashboards`));
    } else if (type.startsWith("energy-")) {
      out.push(v("energy-card", path, `Energy card "${type}" reads energy preferences for all sources`));
    } else if (NEEDS_ENTITIES.has(type) && !hasExplicitEntities(node)) {
      out.push(v("missing-entities", path, `Card type "${type}" must list its entities explicitly`));
    }
    if (type === "map" && node.geo_location_sources !== undefined) {
      out.push(v("dynamic-card", path, "Map card with geo_location_sources shows entities dynamically"));
    }
  }
  // Images of cards, rows, badges and picture elements (anything with a type
  // or an entity), not keys of the same name elsewhere, such as action data.
  if (type || "entity" in node) out.push(...checkImages(node, path));
  return out;
}

/**
 * Image sources: `image`, `dark_mode_image` and the per-state `state_image`
 * values, each a URL or a `{ media_content_id }` object.
 */
function checkImages(node: Obj, path: string): Violation[] {
  const sources: Array<[string, unknown]> = [
    [`${path}.image`, node.image],
    [`${path}.dark_mode_image`, node.dark_mode_image],
  ];
  if (isObj(node.state_image)) {
    for (const [state, value] of Object.entries(node.state_image)) sources.push([`${path}.state_image.${state}`, value]);
  }
  const out: Violation[] = [];
  for (const [at, value] of sources) {
    const source = isObj(value) ? value.media_content_id : value;
    if (typeof source === "string" && !IMAGE_PREFIXES.some((p) => source.startsWith(p))) {
      out.push(v("image-source", at, `Image source "${source}" cannot be verified`));
    }
  }
  return out;
}

function hasExplicitEntities(card: Obj): boolean {
  if (isEntityId(card.entity)) return true;
  if (Array.isArray(card.entities) && card.entities.length > 0) return true;
  return false;
}

function checkAction(action: Obj, path: string, out: Violation[]): void {
  const kind = action.action;
  // navigate and url actions are questions for the admin (see interactions.ts).
  if (kind !== "call-service" && kind !== "perform-action") return;

  let hasEntityTarget = false;
  for (const key of ["target", "data", "service_data"]) {
    const sub = action[key];
    if (!isObj(sub)) continue;
    for (const bad of NON_ENTITY_TARGET_KEYS) {
      if (bad in sub) {
        out.push(v("non-entity-target", `${path}.${key}.${bad}`, `Service targets by ${bad} cannot be mapped to entities`));
      }
    }
    const ids = sub.entity_id;
    if (isEntityId(ids) || (Array.isArray(ids) && ids.length > 0 && ids.every(isEntityId))) {
      hasEntityTarget = true;
    } else if (ids !== undefined) {
      out.push(v("non-entity-target", `${path}.${key}.entity_id`, `entity_id "${String(ids)}" is not a plain entity id`));
    }
  }
  if (!hasEntityTarget) {
    out.push(v("no-entity-target", path, "Service actions must target explicit entity ids"));
  }
}
