import { hasTemplate, isEntityId, isObj, type Obj } from "./extract";
import { ACTION_KEYS } from "./interactions";

export interface Violation {
  rule: string;
  /** JSON-path-ish location inside the dashboard config */
  path: string;
  message: string;
}

const NON_ENTITY_TARGET_KEYS = ["area_id", "device_id", "label_id", "floor_id"];
/** Card types that pick entities at runtime instead of listing them. */
const DYNAMIC_CARD_TYPES = new Set(["area", "iframe"]);
/** Card types that need an explicit entity list to be analysable. */
const NEEDS_ENTITIES = new Set(["logbook", "history-graph", "statistics-graph", "statistic", "map"]);
const IMAGE_PREFIXES = ["media-source://", "/local/", "/api/image/serve/", "http://", "https://", "data:image/"];

/**
 * Checks whether a dashboard can be safely used as an allowlist source.
 * Returns an empty array when the dashboard is acceptable.
 */
export function validate(config: Obj): Violation[] {
  const violations: Violation[] = [];

  if ("strategy" in config) {
    violations.push(v("strategy", "$", "Dashboard is generated by a strategy; entities are computed client-side from all states"));
  }

  walk(config, "$", violations, null);
  return violations;
}

function v(rule: string, path: string, message: string): Violation {
  return { rule, path, message };
}

function walk(node: unknown, path: string, out: Violation[], parent: Obj | null): void {
  if (Array.isArray(node)) {
    node.forEach((item, i) => walk(item, `${path}[${i}]`, out, parent));
    return;
  }
  if (!isObj(node)) return;

  if ("strategy" in node && path !== "$") {
    out.push(v("strategy", path, "View is generated by a strategy; entities are computed client-side from all states"));
  }

  const type = typeof node.type === "string" ? node.type : undefined;
  if (type) {
    if (type.startsWith("custom:")) {
      out.push(v("custom-card", path, `Custom element "${type}" cannot be analysed`));
    } else if (DYNAMIC_CARD_TYPES.has(type)) {
      out.push(v("dynamic-card", path, `Card type "${type}" is not allowed on guest dashboards`));
    } else if (type.startsWith("energy-")) {
      out.push(v("energy-card", path, `Energy card "${type}" reads energy preferences for all sources`));
    } else if (NEEDS_ENTITIES.has(type) && !hasExplicitEntities(node)) {
      out.push(v("missing-entities", path, `Card type "${type}" must list its entities explicitly`));
    }
    if (type === "map" && node.geo_location_sources !== undefined) {
      out.push(v("dynamic-card", path, "Map card with geo_location_sources shows entities dynamically"));
    }
    if (type.startsWith("picture") && typeof node.image === "string" && !IMAGE_PREFIXES.some((p) => (node.image as string).startsWith(p))) {
      out.push(v("image-source", `${path}.image`, `Image source "${node.image}" cannot be verified`));
    }
  }

  for (const [key, value] of Object.entries(node)) {
    const childPath = `${path}.${key}`;
    // Strategy objects are already a violation; their contents are not cards.
    if (key === "strategy") continue;

    if (ACTION_KEYS.has(key) && isObj(value)) {
      checkAction(value, childPath, out);
    }

    if (hasTemplate(value) && !(key === "content" && type === "markdown")) {
      out.push(v("template", childPath, "Templates are only allowed in markdown card content"));
    }

    walk(value, childPath, out, node);
  }
}

function hasExplicitEntities(card: Obj): boolean {
  if (isEntityId(card.entity)) return true;
  if (Array.isArray(card.entities) && card.entities.length > 0) return true;
  return false;
}

function checkAction(action: Obj, path: string, out: Violation[]): void {
  const kind = action.action;
  // navigate and url actions are questions for the admin (see interactions.ts).
  if (kind !== "call-service" && kind !== "perform-action") return;

  let hasEntityTarget = false;
  for (const key of ["target", "data", "service_data"]) {
    const sub = action[key];
    if (!isObj(sub)) continue;
    for (const bad of NON_ENTITY_TARGET_KEYS) {
      if (bad in sub) {
        out.push(v("non-entity-target", `${path}.${key}.${bad}`, `Service targets by ${bad} cannot be mapped to entities`));
      }
    }
    const ids = sub.entity_id;
    if (isEntityId(ids) || (Array.isArray(ids) && ids.length > 0 && ids.every(isEntityId))) {
      hasEntityTarget = true;
    } else if (ids !== undefined) {
      out.push(v("non-entity-target", `${path}.${key}.entity_id`, `entity_id "${String(ids)}" is not a plain entity id`));
    }
  }
  if (!hasEntityTarget) {
    out.push(v("no-entity-target", path, "Service actions must target explicit entity ids"));
  }
}
